sonar.projectKey=kazuma-desu_etcd-compass
sonar.organization=kazuma-desu
sonar.projectName=etcd-compass

sonar.sources=src,src-tauri/src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.exclusions=src-tauri/target/**,node_modules/**,dist/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.rust.lcov.reportPaths=backend-coverage/lcov.info
sonar.rust.clippy.enabled=false

sonar.sourceEncoding=UTF-8
